site_name: CS2100DE Labs
# site_url: https://nus-cs2100de.github.io/labs
theme:
  name: material
  palette:
    scheme: nus
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Lab manuals: 
    - Lab 1: manuals/01/lab_01.md
    - Lab 2: manuals/02/lab_02.md
    - Lab 3: manuals/03/lab_03.md
    - Lab 4: manuals/04/lab_04.md
    - Lab 5: manuals/05/lab_05.md
    - Lab 6: manuals/06/lab_06.md
    - Lab 7: manuals/07/lab_07.md
    - Lab 8: manuals/08/lab_08.md
  - Tool setup guides:
    - Installation guide for Vivado (from CG3207): https://nus-cg3207.github.io/labs/Vivado_Installation_and_Getting_Started/vivado_install_guide/